autoDeploy: true
plan: starter

services:
  - type: web
    name: tgst-empire
    env: node
    repo: https://github.com/johny-1992/TGST
    branch: main
    buildCommand: |
      # Si frontend existe
      if [ -f ./frontend/package.json ]; then
        cd frontend && npm install && cd ..
      fi
      # Si requirements.txt existe pour backend
      if [ -f ./requirements.txt ]; then
        pip install -r requirements.txt
      fi
    startCommand: |
      # Démarre le frontend Remix
      if [ -f ./frontend/package.json ]; then
        cd frontend && npm run start &
        cd ..
      fi
      # Démarre un bot Python ou Node
      if [ -f ./main.py ]; then
        python main.py &
      elif [ -f ./index.js ]; then
        node index.js &
      fi
      # Garde le process vivant
      wait
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRIVATE_KEY
        fromSecret: PRIVATE_KEY
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: INFURA_API
        fromSecret: INFURA_API
      - key: SITE_URL
        value: https://tgst-site.onrender.com
      - key: APP_URL
        value: https://tgst-app.onrender.com
      - key: BOT_URL
        value: https://tgst-bot.onrender.com
      - key: DASHBOARD_URL
        value: https://tgst-dashboard.onrender.com
