
name = "tgst1"
main = "server.js"
compatibility_date = "2025-08-19"

[vars]
# Tes variables d'environnement (exemple)
NODE_ENV = "production"
PORT = "8080"

[build]
command = "npm install && npm run build"

[deploy]
command = "npm start"

[site]
bucket = "./public"
entry-point = "."
