name = "tgst-worker"
type = "javascript"
account_id = "TON_ACCOUNT_ID"
workers_dev = true
compatibility_date = "2025-08-19"

[vars]
PRIVATE_KEY = "YOUR_PRIVATE_KEY"
BOT_TOKEN = "YOUR_BOT_TOKEN"
INFURA_API = "YOUR_INFURA_API"
SITE_URL = "https://tgst-site.onrender.com"
APP_URL = "https://tgst-app.onrender.com"
BOT_URL = "https://tgst-bot.onrender.com"

Toutes les variables sensibles restent dans Cloudflare.

Prêt à déployer en un clic avec wrangler deploy.

