name = "tgst-worker"
main = "index.js"
compatibility_date = "2025-08-19"
type = "javascript"
account_id = "{{YOUR_CLOUDFLARE_ACCOUNT_ID}}"
workers_dev = true

[vars]
PRIVATE_KEY = "{{env:PRIVATE_KEY}}"
BOT_TOKEN = "{{env:BOT_TOKEN}}"
INFURA_API = "{{env:INFURA_API}}"
SITE_URL = "https://tgst-site.onrender.com"
APP_URL = "https://tgst-app.onrender.com"
BOT_URL = "https://tgst-bot.onrender.com"
DASHBOARD_URL = "https://tgst-dashboard.onrender.com"
