name: TGST Global Orchestrator

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"   # relance toutes les heures

jobs:
  launch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip

      - name: Run TGST Orchestrator
        run: bash launch_tgst.sh
